# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 디스코드 알림봇

on:
  schedule: # UTC+9 기준 22시 실행
    - cron:  "0 14 * * *"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ https://discord.com/api/webhooks/1221994402168311898/NKfa9WZi9opMBrn3OF7lrXZyTEN5HfkyX0qgdWDbjRblXrc1XOdj9ecc6VxJjFRdypzi }}
        content: "오늘 한 일을 적어주세요!"
